services:

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name : wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: postgresql-16
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - data:/wiki/data/content

volumes:
  data:

networks:
  default:
    external: true
    name: base